<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBenhVien_DoAnCuoiKi" Class="QLBVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MINHKHOA\TIN;Initial Catalog=QuanLyBenhVien_DoAnCuoiKi;Integrated Security=True" SettingsObjectName="DoAnCuoiKyQLBVHQT_Final.Properties.Settings" SettingsPropertyName="QuanLyBenhVien_DoAnCuoiKiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BacSi" Member="BacSis">
    <Type Name="BacSi">
      <Column Name="MaBS" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoBS" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TenBS" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spThemBacSi" Method="spThemBacSi">
    <Parameter Name="MaBS" Parameter="maBS" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="HoBS" Parameter="hoBS" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="TenBS" Parameter="tenBS" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="ChucVu" Parameter="chucVu" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="NVarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spLayBacSi" Method="spLayBacSi">
    <ElementType Name="spLayBacSiResult">
      <Column Name="MaBS" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoBS" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TenBS" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>