// <auto-generated />
using System;
using ConsoleApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(HospitalManagementContext))]
    partial class HospitalManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.Models.Account", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("UserID")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("UserId")
                        .HasName("pk_account");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Benh", b =>
                {
                    b.Property<string>("TenBenh")
                        .HasMaxLength(50);

                    b.Property<string>("TrieuChung1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TrieuChung2")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TrieuChung3")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("TenBenh")
                        .HasName("pk_benh");

                    b.ToTable("Benh");
                });

            modelBuilder.Entity("ConsoleApp1.Models.BenhNhan", b =>
                {
                    b.Property<string>("MaBenhNhan")
                        .HasMaxLength(50);

                    b.Property<string>("Benh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TenBenhNhan")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaBenhNhan")
                        .HasName("pk_benhnhan");

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy1", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<string>("Benh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ChiPhi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayXuatVien")
                        .HasColumnType("date");

                    b.HasKey("MaSo")
                        .HasName("pk_doanhthuquy1");

                    b.ToTable("DoanhThuQuy1");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy2", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<string>("Benh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ChiPhi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayXuatVien")
                        .HasColumnType("date");

                    b.HasKey("MaSo")
                        .HasName("pk_doanhthuquy2");

                    b.ToTable("DoanhThuQuy2");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy3", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<string>("Benh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ChiPhi");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayXuatVien")
                        .HasColumnType("date");

                    b.HasKey("MaSo")
                        .HasName("pk_doanhthuquy3");

                    b.ToTable("DoanhThuQuy3");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DsbenhNhanDaXuatVien", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<string>("Benh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaSo")
                        .HasName("pk_dsbenhnhandaxuatvien");

                    b.ToTable("DSBenhNhanDaXuatVien");
                });

            modelBuilder.Entity("ConsoleApp1.Models.HeSoLuong", b =>
                {
                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(50);

                    b.Property<double>("HeSoLuongTheoGio");

                    b.HasKey("NgheNghiep")
                        .HasName("pk_hesoluong");

                    b.ToTable("HeSoLuong");
                });

            modelBuilder.Entity("ConsoleApp1.Models.HoaDon", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<int?>("PhiDieuTri");

                    b.Property<int>("SoLuongThuocA");

                    b.Property<int>("SoLuongThuocB");

                    b.Property<int>("SoLuongThuocC");

                    b.Property<int>("SoLuongThuocD");

                    b.Property<int>("SoLuongThuocE");

                    b.HasKey("MaSo")
                        .HasName("pk_hoadon");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("ConsoleApp1.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasColumnName("MaNV")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SoNgayDiLam");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MaNv")
                        .HasName("pk_nhanvien");

                    b.HasIndex("NgheNghiep");

                    b.HasIndex("TenNhanVien")
                        .IsUnique()
                        .HasName("ck_nhanvien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("ConsoleApp1.Models.PhiDieuTri", b =>
                {
                    b.Property<string>("Benh")
                        .HasMaxLength(50);

                    b.Property<int>("ChiPhi");

                    b.HasKey("Benh")
                        .HasName("pk_phidieutri");

                    b.ToTable("PhiDieuTri");
                });

            modelBuilder.Entity("ConsoleApp1.Models.SoLuongBenhNhan", b =>
                {
                    b.Property<string>("Slbn")
                        .HasColumnName("SLBN")
                        .HasMaxLength(50);

                    b.HasKey("Slbn")
                        .HasName("pk_soluongbenhnhan");

                    b.ToTable("SoLuongBenhNhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.ThongTinBenhNhan", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(50);

                    b.Property<string>("SoPhong")
                        .HasMaxLength(50);

                    b.Property<string>("MshoaDon")
                        .HasColumnName("MSHoaDon")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NgayNhapVien")
                        .HasColumnType("date");

                    b.HasKey("MaSo", "SoPhong", "MshoaDon")
                        .HasName("pk_thongtinbenhnhan");

                    b.HasIndex("MshoaDon");

                    b.ToTable("ThongTinBenhNhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy1", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithOne("DoanhThuQuy1")
                        .HasForeignKey("ConsoleApp1.Models.DoanhThuQuy1", "MaSo")
                        .HasConstraintName("fk_doanhthuquy1_benhnhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy2", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithOne("DoanhThuQuy2")
                        .HasForeignKey("ConsoleApp1.Models.DoanhThuQuy2", "MaSo")
                        .HasConstraintName("fk_doanhthuquy2_benhnhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DoanhThuQuy3", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithOne("DoanhThuQuy3")
                        .HasForeignKey("ConsoleApp1.Models.DoanhThuQuy3", "MaSo")
                        .HasConstraintName("fk_doanhthuquy3_benhnhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.DsbenhNhanDaXuatVien", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithOne("DsbenhNhanDaXuatVien")
                        .HasForeignKey("ConsoleApp1.Models.DsbenhNhanDaXuatVien", "MaSo")
                        .HasConstraintName("fk_dsbenhnhandaxuatvien_benhnhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.HoaDon", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithOne("HoaDon")
                        .HasForeignKey("ConsoleApp1.Models.HoaDon", "MaSo")
                        .HasConstraintName("fk_hoadon_benhnhan");
                });

            modelBuilder.Entity("ConsoleApp1.Models.NhanVien", b =>
                {
                    b.HasOne("ConsoleApp1.Models.HeSoLuong", "NgheNghiepNavigation")
                        .WithMany("NhanVien")
                        .HasForeignKey("NgheNghiep")
                        .HasConstraintName("fk_nhanvien_hesoluong");
                });

            modelBuilder.Entity("ConsoleApp1.Models.PhiDieuTri", b =>
                {
                    b.HasOne("ConsoleApp1.Models.Benh", "BenhNavigation")
                        .WithOne("PhiDieuTri")
                        .HasForeignKey("ConsoleApp1.Models.PhiDieuTri", "Benh")
                        .HasConstraintName("fk_phidieutri_benh");
                });

            modelBuilder.Entity("ConsoleApp1.Models.SoLuongBenhNhan", b =>
                {
                    b.HasOne("ConsoleApp1.Models.HoaDon", "SlbnNavigation")
                        .WithOne("SoLuongBenhNhan")
                        .HasForeignKey("ConsoleApp1.Models.SoLuongBenhNhan", "Slbn")
                        .HasConstraintName("fk_soluongbenhnhan_hoadon");
                });

            modelBuilder.Entity("ConsoleApp1.Models.ThongTinBenhNhan", b =>
                {
                    b.HasOne("ConsoleApp1.Models.BenhNhan", "MaSoNavigation")
                        .WithMany("ThongTinBenhNhan")
                        .HasForeignKey("MaSo")
                        .HasConstraintName("fk_thongtinbenhnhan_benhnhan");

                    b.HasOne("ConsoleApp1.Models.HoaDon", "MshoaDonNavigation")
                        .WithMany("ThongTinBenhNhan")
                        .HasForeignKey("MshoaDon")
                        .HasConstraintName("fk_thongtinbenhnhan_hoadon");
                });
#pragma warning restore 612, 618
        }
    }
}
